import type { Playbook } from "./types";

const k = (id: string, label: string, key: string): Playbook["steps"][number] => ({
  id,
  tool: "key",
  label,
  key,
});
const t = (id: string, label: string, text: string): Playbook["steps"][number] => ({
  id,
  tool: "type",
  label,
  text,
  submit: true,
});
const w = (id: string, label: string, needle: string, timeoutMs = 9000): Playbook["steps"][number] => ({
  id,
  tool: "wait",
  label,
  needle,
  timeoutMs,
});
const a = (id: string, label: string, needle: string): Playbook["steps"][number] => ({
  id,
  tool: "assert",
  label,
  needle,
});

export const PLAYBOOKS: Playbook[] = [
  {
    id: "full-release",
    name: "Full RELEASE Gate",
    nameZh: "完整 RELEASE",
    blurb: "POST → Aptio 身份與 CPU/Security 旋鈕 → UEFI Shell SMBIOS → OS reltest。",
    stages: ["POST", "BIOS", "SHELL", "OS"],
    steps: [
      { id: "pwr", tool: "power", action: "cycle", label: "ATX 冷開機 / 循環電源" },
      w("post", "等待 POST 提示", "Press DEL", 10000),
      k("del", "DEL 進入 Setup", "Delete"),
      w("aptio", "等待 Aptio Setup", "Aptio Setup Utility"),
      a("ver", "核對 BIOS Version", "{{biosVersion}}"),
      a("tag", "核對 RELEASE 標籤", "{{biosTag}}"),
      a("vendor", "核對 Vendor", "{{vendor}}"),
      k("adv", "切到 Advanced", "ArrowRight"),
      w("cpu", "看到 CPU Configuration", "CPU Configuration"),
      k("ent-cpu", "進入 CPU Configuration", "Enter"),
      w("vtx", "看到 Virtualization", "Virtualization"),
      a("vtx-on", "VT-x / AMD-V = Enabled", "Enabled"),
      k("esc-cpu", "離開 CPU 選單", "Escape"),
      k("r2", "Chipset", "ArrowRight"),
      k("r3", "Boot", "ArrowRight"),
      k("r4", "Security", "ArrowRight"),
      w("sb", "看到 Secure Boot", "Secure Boot"),
      a("sb-on", "Secure Boot = Enabled", "Secure Boot"),
      k("r5", "Save & Exit", "ArrowRight"),
      w("exit", "Save & Exit 頁", "Boot Override: UEFI Shell"),
      k("d1", "下移", "ArrowDown"),
      k("d2", "下移", "ArrowDown"),
      k("d3", "下移", "ArrowDown"),
      k("d4", "下移", "ArrowDown"),
      k("d5", "Boot Override Shell", "ArrowDown"),
      k("go-shell", "進入 UEFI Shell", "Enter"),
      w("shell", "等待 UEFI Shell", "UEFI Interactive Shell", 8000),
      t("ver-sh", "Shell: ver", "ver"),
      w("edk", "核對 EDK II", "EDK II"),
      t("smbios", "Shell: smbiosview -t 0", "smbiosview -t 0"),
      w("sm-ver", "SMBIOS Type 0 版本", "BIOS Version: {{biosVersion}}"),
      t("relinfo", "Shell: relinfo", "relinfo"),
      w("relpass", "RELINFO PASS", "RELINFO PASS"),
      t("reset", "Shell: reset", "reset"),
      w("post2", "等待再次 POST", "Press DEL", 10000),
      k("f12", "F12 Boot Menu", "F12"),
      w("bm", "Boot Menu", "Please select boot device"),
      k("osboot", "Boot NVMe0", "Enter"),
      w("os", "等待 OS", "root@", 12000),
      t("reltest", "OS: reltest --smoke", "reltest --smoke"),
      w("os-pass", "RELTEST PASS", "RELTEST PASS", 6000),
    ],
  },
  {
    id: "post-id",
    name: "POST Identity",
    nameZh: "POST / BIOS 身份",
    blurb: "進 Setup，核對 Vendor、Version、Date 與主板型號。",
    stages: ["POST", "BIOS"],
    steps: [
      { id: "pwr", tool: "power", action: "cycle", label: "循環電源" },
      w("post", "等待 POST", "Press DEL", 10000),
      k("del", "DEL", "Delete"),
      w("aptio", "Aptio Setup", "Aptio Setup Utility"),
      a("ver", "BIOS Version", "{{biosVersion}}"),
      a("date", "BIOS Date", "{{biosDate}}"),
      a("board", "Board Name", "{{board}}"),
      k("sys", "下移到 System Information", "ArrowDown"),
      k("sys2", "下移", "ArrowDown"),
      k("sys3", "下移", "ArrowDown"),
      k("sys4", "下移", "ArrowDown"),
      k("enter", "進入 System Information", "Enter"),
      w("cpu", "看到 Processor", "Processor"),
      a("serial", "Serial", "{{serial}}"),
    ],
  },
  {
    id: "shell-diag",
    name: "UEFI Shell Diagnostics",
    nameZh: "UEFI Shell 診斷",
    blurb: "F12 進 Shell，跑 ver / map / smbiosview / memmap / relinfo。",
    stages: ["POST", "SHELL"],
    steps: [
      { id: "pwr", tool: "power", action: "cycle", label: "循環電源" },
      w("post", "等待 POST", "Press DEL", 10000),
      k("f12", "F12 Boot Menu", "F12"),
      w("bm", "Boot Menu", "Please select boot device"),
      k("up", "選 EFI Shell", "ArrowUp"),
      k("go", "Enter", "Enter"),
      w("shell", "UEFI Shell", "UEFI Interactive Shell", 8000),
      t("ver", "ver", "ver"),
      w("edk", "EDK II", "EDK II"),
      t("map", "map", "map"),
      w("fs0", "FS0 mapping", "FS0:"),
      t("smbios", "smbiosview -t 0", "smbiosview -t 0"),
      w("t0", "Type 0", "Type 0 : BIOS Information"),
      a("ver2", "Version", "{{biosVersion}}"),
      t("mem", "memmap", "memmap"),
      w("avail", "Available memory", "Available"),
      t("pci", "pci", "pci"),
      w("nvme", "NVMe device", "NVMe"),
      t("rel", "relinfo", "relinfo"),
      w("ok", "RELINFO PASS", "RELINFO PASS"),
    ],
  },
  {
    id: "os-smoke",
    name: "OS Smoke",
    nameZh: "OS Smoke",
    blurb: "F12 開 NVMe，跑 dmidecode 與 reltest --smoke。",
    stages: ["POST", "OS"],
    steps: [
      { id: "pwr", tool: "power", action: "cycle", label: "循環電源" },
      w("post", "等待 POST", "Press DEL", 10000),
      k("f12", "F12 Boot Menu", "F12"),
      w("bm", "Boot Menu", "Please select boot device"),
      k("go", "Boot NVMe0", "Enter"),
      w("os", "OS prompt", "root@", 12000),
      t("dmi", "dmidecode -t bios", "dmidecode -t bios"),
      w("dver", "dmidecode 版本", "Version: {{biosVersion}}"),
      t("lscpu", "lscpu", "lscpu"),
      w("virt", "Virtualization", "Virtualization"),
      t("rel", "reltest --smoke", "reltest --smoke"),
      w("ok", "RELTEST PASS", "RELTEST PASS"),
    ],
  },
  {
    id: "knobs",
    name: "CPU / Security Knobs",
    nameZh: "旋鈕檢查",
    blurb: "Advanced CPU 與 Security 頁，確認 VT-x、SB、TPM 預設。",
    stages: ["POST", "BIOS"],
    steps: [
      { id: "pwr", tool: "power", action: "cycle", label: "循環電源" },
      w("post", "等待 POST", "Press DEL", 10000),
      k("del", "DEL", "Delete"),
      w("aptio", "Aptio", "Aptio Setup Utility"),
      k("adv", "Advanced", "ArrowRight"),
      k("cpu", "CPU Configuration", "Enter"),
      w("v", "Virtualization", "Intel Virtualization Technology"),
      a("on", "Enabled", "Enabled"),
      k("esc", "Esc", "Escape"),
      k("c1", "Chipset", "ArrowRight"),
      k("c2", "Boot", "ArrowRight"),
      k("c3", "Security", "ArrowRight"),
      w("sec", "Security 頁", "Secure Boot"),
      a("sb", "Secure Boot", "Secure Boot"),
      a("tpm", "TPM 2.0", "TPM 2.0"),
    ],
  },
];

export const STEP_KEYS = [
  "Delete",
  "Escape",
  "Enter",
  "Tab",
  "Backspace",
  "F1",
  "F2",
  "F3",
  "F4",
  "F5",
  "F6",
  "F7",
  "F8",
  "F9",
  "F10",
  "F11",
  "F12",
  "ArrowUp",
  "ArrowDown",
  "ArrowLeft",
  "ArrowRight",
  "Home",
  "End",
  "PageUp",
  "PageDown",
  "Insert",
  " ",
  "Control+Alt+Delete",
] as const;


export const STEP_PRESETS: { label: string; step: Omit<Playbook["steps"][number], "id"> }[] = [
  { label: "循環電源", step: { tool: "power", action: "cycle", label: "循環電源" } },
  { label: "開機", step: { tool: "power", action: "on", label: "開機" } },
  { label: "關機", step: { tool: "power", action: "off", label: "關機" } },
  { label: "等 POST / DEL", step: { tool: "wait", label: "等待 POST 提示", needle: "Press DEL", timeoutMs: 10000 } },
  { label: "DEL 進 Setup", step: { tool: "key", key: "Delete", label: "DEL 進入 Setup" } },
  { label: "F12 Boot Menu", step: { tool: "key", key: "F12", label: "F12 Boot Menu" } },
  { label: "方向鍵 ↓", step: { tool: "key", key: "ArrowDown", label: "下移" } },
  { label: "方向鍵 ↑", step: { tool: "key", key: "ArrowUp", label: "上移" } },
  { label: "方向鍵 →", step: { tool: "key", key: "ArrowRight", label: "右移 / 換頁" } },
  { label: "方向鍵 ←", step: { tool: "key", key: "ArrowLeft", label: "左移 / 換頁" } },
  { label: "Enter", step: { tool: "key", key: "Enter", label: "Enter" } },
  { label: "Esc", step: { tool: "key", key: "Escape", label: "Esc" } },
  { label: "等畫面文字", step: { tool: "wait", label: "等待畫面", needle: "", timeoutMs: 8000 } },
  { label: "核對畫面文字", step: { tool: "assert", label: "核對畫面", needle: "" } },
  { label: "輸入並送出", step: { tool: "type", label: "輸入指令", text: "", submit: true } },
  { label: "掛 virtual media", step: { tool: "mount", label: "掛 rel-test-agent.iso", iso: true } },
  { label: "等待 ms", step: { tool: "sleep", label: "等待", ms: 400 } },
];

export function blankCustom(from?: Playbook): Playbook {
  const id = `custom-${Date.now()}`;
  if (from) {
    return {
      ...from,
      id,
      name: `${from.name} (custom)`,
      nameZh: `${from.nameZh}（自訂）`,
      steps: from.steps.map((s, i) => ({ ...s, id: `${id}-s${i}` })),
      custom: true,
    };
  }
  return {
    id,
    name: "Custom RELEASE",
    nameZh: "新流程",
    blurb: "自訂 BIOS / Shell / OS 步驟。",
    stages: ["POST", "BIOS"],
    custom: true,
    steps: [
      { id: `${id}-s0`, tool: "power", action: "cycle", label: "循環電源" },
      {
        id: `${id}-s1`,
        tool: "wait",
        label: "等待 POST 提示",
        needle: "Press DEL",
        timeoutMs: 10000,
      },
    ],
  };
}

export const TOOL_CATALOG = [
  {
    name: "power",
    rpc: "kvm.atx.setPower",
    hint: "on | off | cycle — 走 JetKVM ATX 擴充腳。",
  },
  {
    name: "key",
    rpc: "kvm.hid.key",
    hint: "USB HID 掃描碼。BIOS 用 DEL / 方向鍵 / F12 / F10。",
  },
  {
    name: "type",
    rpc: "kvm.hid.text",
    hint: "字串逐字送 HID，submit 再送 Enter。Shell 與 OS 用。",
  },
  {
    name: "wait",
    rpc: "kvm.video.ocrWait",
    hint: "對 HDMI 畫面做 OCR，等到針出現。",
  },
  {
    name: "assert",
    rpc: "rel.assert.ocr",
    hint: "當下畫面必須包含針，否則 FAIL。",
  },
  {
    name: "sleep",
    rpc: "rel.sleep",
    hint: "固定等待，少用，優先 wait。",
  },
  {
    name: "mount",
    rpc: "kvm.virtualMedia.mount",
    hint: "掛 RELEASE agent ISO 到 DUT USB。",
  },
] as const;
